# config/meta.yml
meta_title: "Timzy - Keep your project history on track"
meta_description: "The best lessons come from experience and that's why you should always keep track of your website's projects and their impacts on your traffic. 'Know what? With Timzy, that's easy ! "
meta_image: "social_media.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@timzy_app" # indispensable pour les Twitter Cards
